nzp-team/vril-engine

source/psp/video_hardware_draw.cpp
Should allow for bigger heap allocations without ending up with a bad_alloc.
=> Replace texture allocations to use the hunk.

source/modelgen.h, source/psp/video_hardware.h, source/psp/video_hardware_main.cpp, source/psp/video_hardware_mesh.cpp, source/psp/video_hardware_misc.cpp, source/psp/video_hardware_model.cpp
Ports changes from interstices compressed verts, removes per vertex shading, and allocates models verts all at once. Also cleans up unused code from video_hardware_main a bit.
=> Speedier alias model rendering

source/psp/video_hardware.h, source/psp/video_hardware_main.cpp, source/psp/video_hardware_model.h, source/psp/video_hardware_surface.cpp, source/psp/video_hardware_warp.cpp
needed to add separate frustum check sphere and box because of rotating bmodels, otherwise near identical with interstice
=> Port broad phase clipping checks from interstice

source/cl_main.c, source/client.h, source/psp/video_hardware_main.cpp, source/psp/video_hardware_surface.cpp
Detects brush models that are at 0 0 0 and with angles 0 0 0, which can then be drawn together with world. Exceptions apply to brushes using HL render modes. I noticed that rendermodes TEXTURE and SOLID work the same and don't work as specified, so I wrote that down and made them both work explicitly like fences with lightmaps (which means improved visuals). These changes improve performance by a few frames in the tricky spot. I went through custom maps and didn't see negative side effects to fence textures being lightmapped. In addition, lightmapped fences no longer darken or brighten the colors behind the transparent parts.
=> Render static brush models with world

source/psp/video_hardware_surface.cpp
regression from my previous work
=> Fix doors/obstacles losing their lightmaps when they're moving

source/mathlib.h, source/pr_cmds.c, source/pr_edict.c, source/quakedef.h, source/sv_main.c
This gives zombies and players (and other entities) a stored value for last waypoint that is then used to try find a good comparison for closest visible checkpoint to begin with. Saves *a ton* of SV_Move calls which were causing the huge hitches previously.
Also fixes waypoint id 0 to be valid, previously the engine made sure it can't be used but not very clearly...
=> Even faster pathfinding

source/draw.h, source/host.c, source/menu.c, source/psp/video_hardware.h, source/psp/video_hardware_QMB.cpp, source/psp/video_hardware_draw.cpp, source/psp/video_hardware_hlmdl.cpp, source/psp/video_hardware_main.cpp, source/psp/video_hardware_misc.cpp, source/psp/video_hardware_model.cpp, source/psp/video_hardware_screen.cpp, source/render.h
Changed texture management to not use the c++ list, but hook it with gltextures. Properly clear all non-permanent gltextures on every reload. This also allowed us to not keep the menu pics in memory when actually playing.
Fixed at least one memory leak as well. Memory use seems kind of stable when reloading maps a few times.
=> Simplify resource management

source/console.c, source/psp/video_hardware.h, source/psp/video_hardware_QMB.cpp, source/psp/video_hardware_decals_QMB.cpp, source/psp/video_hardware_draw.cpp, source/psp/video_hardware_fog.cpp, source/psp/video_hardware_images.cpp, source/psp/video_hardware_main.cpp, source/psp/video_hardware_misc.cpp, source/psp/video_hardware_surface.cpp, source/psp/video_hardware_warp.cpp
There's also bunch of slightly unrelated changes to reduce vram use by other unused assets. This buys us enough vram to store every texture on ndu including sky in vram, and it means sky should be usable on phat too.
=> Add horizon fog blending for sky

source/wii/gx/gx_draw.c, source/wii/gx/gx_rmain.c, source/wii/gx/video_gx.c, source/wii/main.c
=> RVL: Proper Widescreen Support

Makefile.rvl, source/wii/gx/gx_draw.c
---
Made sure text filter is always linear, also fixes the Makefile TARGETDIR
---
Current:
With this change:
---
=> RVL: Fix Text Filtering

source/wii/cdaudio.c, source/wii/main.c
---
Changes CDAudio logic to allow volume to be manipulated in the settings menu. 
---
N/A
---
=> RVL: Allow CDMusic volume to be modified in the settings menu

.github/workflows/builds.yml, testing/run_tests.sh, testing/setup/psp.sh, testing/setup/utils/ppsspp.patch, testing/tests/map-boot.sh
---
Creates a patch for PPSSPP that we apply after cloning that allows us to test simulating a PSP-1000 unit, and creates an additional job to use this flag so we test both low mem and high mem PSP models.
---
N/A
---
=> PR: Add PSP-1000 support to Vril tests

Makefile.ctr, Makefile.psp, Makefile.rvl
To run a build with the GCC static analyzer, use a command like:
make -f Makefile.ctr FANALYZER=1
Add a new variable to check to enable -fanalyzer when running builds.
---
```
$ make -f Makefile.ctr FANALYZER=1
test_handler.c
chase.c
...
C:/msys64/home/peter/vril-engine/source/wad.c: In function 'ConvertWad3ToRGBA':
C:/msys64/home/peter/vril-engine/source/wad.c:262:28: warning: dereference of possibly-NULL 'data' [CWE-690] [-Wanalyzer-possible-null-dereference]
262 |          ((int *) data)[i] = 0;
|          ~~~~~~~~~~~~~~~~~~^~~
'ConvertWad3ToRGBA': events 1-6
|
|  256 |    data = malloc(image_size * 4); // Baker
|      |           ^~~~~~~~~~~~~~~~~~~~~~
|      |           |
|      |           (1) this call could return NULL
|......
|  259 |    for (i = 0; i < image_size; i++) {
| …
```
=> GLOBAL: BUILD: Add fanalyzer option to Makefiles

source/mathlib.c
---
Fixes a regression in mathlib's `AngleVectors` where roll calculation kept a 360 divisor instead of an expected 180.
---
=> GLOBAL: Fix regression in mathlib due to incorrect roll constant

source/cl_main.c, source/platform/ctr/client.h, source/platform/ctr/in_ctr.c, source/platform/ctr/menu.c, source/platform/psp/client.h, source/platform/psp/input.cpp, source/platform/psp/menu.c
---
Adds support for the right analog nub on PlayStation Portable. This is applicable in the following contexts:
- When running on Adrenaline, on PS VITA
- When using a DualShock 3 on PSP GO
- PPSSPP
---
https://github.com/user-attachments/assets/4caf4535-4c52-4abe-9f50-e60fccb6fb07
---
=> PSP: Add support for right analog stick on PSVITA/PSP GO

Makefile.ctr
Add -std=gnu99 to the CFLAGS. GCC 15 changed the default C standard from C17 to C23, which broke the build.
It's best to specify it explicitly so we don't have those problems in the future.
see #77 for some of the errors.
-std=gnu99 is used instead of c99 because it caused some further build errors for missing functions strcasecmp and strlcpy.
The PSP doesn't need this change because it uses C++.
---
=> 3DS: Specify C standard explicitly

source/platform/psp/gu/gu_draw.cpp, source/platform/psp/gu/gu_psp.cpp
---
- Fixes https://github.com/nzp-team/nzportable/issues/404
- Do sceGuTexMode before touching the CLUT fixes issue, if we set the CLUT while we're still in DXT1 mode from sky, it messes up.
- Removed an extra quake palette set when drawing CLUT4 textures, might improve perf
- Set appropriate size for dcacheWriteback when setting CLUT4 palette 
---
(The visual big in the issue no longer happens)
---
=> PSP: Fix corrupted palette issue on Temple and Bunker-Defense

source/cl_parse.c, source/sv_main.c
---
Promotes the current mag count (both primary and secondary) in client stats from byte to short. This fixes nzp-team/nzportable#1162.
---
From nzp-team/nzportable#1162, here's the current behavior:
https://github.com/user-attachments/assets/1ace83d7-d12e-431c-9232-7ff2f1c861e4
---
=> GLOBAL: Promote currentmag to short

Makefile.psp, source/platform/psp/gu/gu_main.cpp
---
PSPSDK has updated to GCC 15, so by default is compiling with newer C standards. Similar to #78 this PR ensures we explicitly use C99. It also updates the use of `sceGuScissor` to reflect the changes found in https://github.com/pspdev/pspsdk/pull/295
---
N/A
---
=> PSP: Explicitly set GNU C99; update sceGuScissor call

source/cl_hud.c, source/cmd.c
This Pull Request adds a backup loading strategy for executing files through the console. This is done in order to add support for loading `nzp.rc` (and thus other config files) inside or outside of a PAK file for the TI-NPSIRE. 
This may cause a slight loading delay on other platforms in the case that a requested file cannot be found since we attempt to load it twice. However, this should not have meaningful user impact. 
Console prior to fix:
Console after fix: 
---
=> TNS: Fix config file and nzp.rc loading

source/cl_parse.c
---
Fixes a crash that could occur on CTR with levels that have a lot of sounds, this stemmed from a legacy feature where the loading screen would print the sound currently being precached, stored into a buffer and updated with `strcpy`. Because it is legacy I just removed this line.
---
N/A
---
=> CTR: Fix crashes with sound name overflow

source/cl_hud.c, source/cl_parse.c, source/pr_cmds.c, source/protocol.h, source/sv_main.c
---
Adds preliminary support for gamemodes to prevent game crashing when the QuakeC changes are introduced
---
N/A
---
=> GLOBAL: Preliminary gamemode support

source/cl_hud.c, source/platform/nspire/draw.c, source/platform/nspire/screen.c
---
This Pull Request adjusts several quality of life improvements for the NSPIRE builds. 
- Remove irrelevant use button mapping and replace with a print of the mapped key during useprints
- Flesh out Draw_ColoredString and Draw_ColorPic to support White to Yellow and White to Red mappings that were prototyped in SDL
- Adopt dithering when drawing advanced pictures that were also prototyped in SDL
Dependent Assets Pull Request: https://github.com/nzp-team/assets/pull/111
---
---
=> TNS: Add dithered and color hacks from SDL

source/platform/psp/gu/gu_draw.cpp
---
Refactors the standard “+” crosshair (also used for grenade) for pixel-perfect centering. Adds local variables (crosshair arm length, crosshair arm thickness, center adjustment) to make the positioning clearer and make tweaks to size and spacing easier.
---
Screenshots at 1x resolution in PPSSPP:
| Before | After |
|:---:|:---:|
| <img src="https://github.com/user-attachments/assets/0e4f8a48-979c-4560-9044-4e4202012280" width="300" alt="Original crosshair (debug on)" /> | <img src="https://github.com/user-attachments/assets/7331c5d4-d61b-47c8-8603-dd06e95c7c04" width="300" alt="Updated crosshair (debug on)" /> |
| Top/Left Gap: 17px, Bottom/Right Gap: 16px | Top/Left Gap: 20px, Bottom/Right Gap: 20px |
Lines up with CrossHairWeapon stat here (i * 0.68 + 6): …
=> PSP: Fix crosshair alignment

source/platform/psp/gu/gu_model.cpp
---
Deprecated old/broken function for loading perk view-model skins 
---
https://github.com/user-attachments/assets/633acf26-683a-4004-ac0f-0be177f9c138
---
=> PSP: Fixed view model screen being incorrect while drinking perks
